version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/repos/sandbox-discord-bot
hooks:
  AfterInstall:
    - location: hooks/install.sh
      timeout: 300
  ApplicationStart:
    - location: hooks/start.sh
      timeout: 3300
